---
abstract: 'A wrapper around the annovar annotation pipeline'
author:
  - 'Jillian Rowe, C<< <jillian.e.rowe at gmail.com> >>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build::Tiny: '0.036'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Annovar-Wrapper
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Cwd: '0'
  Data::Dumper: '0'
  DateTime: '0'
  File::Basename: '0'
  File::Find::Rule: '0'
  File::FindLib: '0'
  File::Path: '0'
  IO::Uncompress::Gunzip: '0'
  Moose: '0'
  MooseX::Getopt: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/jerowe/Annovar-Wrapper/issues
  homepage: https://github.com/jerowe/Annovar-Wrapper
  repository: https://github.com/jerowe/Annovar-Wrapper.git
version: '0.03'
x_contributors:
  - 'Jillian Rowe <jir2004@qatar-med.cornell.edu>'
